import {
  COLOR_DEF_CAUTION,
  COLOR_DEF_DANGER,
  COLOR_DEF_DARK,
  COLOR_DEF_LIGHT,
  COLOR_DEF_PRIMARY,
  COLOR_DEF_SECONDARY,
  COLOR_DEF_SUCCESS,
} from "./index";

export const ThemeColorsTypes = [
  COLOR_DEF_LIGHT,
  COLOR_DEF_DARK,
  COLOR_DEF_PRIMARY,
  COLOR_DEF_SECONDARY,
  COLOR_DEF_SUCCESS,
  COLOR_DEF_CAUTION,
  COLOR_DEF_DANGER,
  "",
] as const;
