import {
  COLOR_CAUTION,
  COLOR_DANGER,
  COLOR_DARK,
  COLOR_LIGHT,
  COLOR_PRIMARY,
  COLOR_SECONDARY,
  COLOR_SUCCESS,
} from "./index";

export const ThemeColorsTypes = [
  COLOR_LIGHT,
  COLOR_DARK,
  COLOR_PRIMARY,
  COLOR_SECONDARY,
  COLOR_SUCCESS,
  COLOR_CAUTION,
  COLOR_DANGER,
  "",
] as const;
